---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: italians
  labels:
    app: italians
spec:
  replicas: 1
  selector:
    matchLabels:
      app: italians
  template:
    metadata:
      labels:
        app: italians
    spec:
      containers:
      - name: italians
        image: robertbrem/italians:0.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /italians/resources/food
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: italians
spec:
  selector:
    app: italians
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081
  type: NodePort
